-- 1.Find the total number of customers in each state

SELECT 
    customer_state, COUNT(customer_id) AS total_customers
FROM
    customers
GROUP BY customer_state;


-- 2.Display the top 10 cities with the highest number of customers

SELECT 
    customer_city, COUNT(customer_id) AS total_customers
FROM
    customers
GROUP BY customer_city
ORDER BY total_customers DESC
LIMIT 10;


-- 3.Count the total number of orders placed each month

SELECT
    YEAR(order_purchase_timestamp) AS order_year,
    MONTH(order_purchase_timestamp) AS order_month,
    COUNT(order_id) AS total_orders
FROM orders
GROUP BY YEAR(order_purchase_timestamp),
         MONTH(order_purchase_timestamp)
ORDER BY order_year, order_month;


-- 4.Find the number of delivered, canceled, and shipped orders

SELECT 
    order_status, COUNT(customer_id) AS total_customers
FROM
    orders
GROUP BY order_status;


-- 5.List the top 10 sellers based on the number of orders

SELECT
    oi.seller_id,
    COUNT(DISTINCT oi.order_id) AS total_orders
FROM order_items oi
GROUP BY oi.seller_id
ORDER BY total_orders DESC
LIMIT 10;


-- 6.Calculate the total revenue generated by each seller

SELECT
    s.seller_id,
    s.seller_city,
    s.seller_state,
    ROUND(SUM(oi.price), 2) AS total_revenue
FROM sellers s
JOIN order_items oi
    ON s.seller_id = oi.seller_id
GROUP BY s.seller_id, s.seller_city, s.seller_state
ORDER BY total_revenue DESC;


-- 7.Find the top 10 best-selling products based on quantity sold

SELECT 
    p.product_id,
    p.product_category_name,
    SUM(oi.order_item_id) AS total_quantity_sold
FROM
    products p
        JOIN
    order_items oi ON p.product_id = oi.product_id
GROUP BY p.product_id , p.product_category_name
ORDER BY total_quantity_sold DESC
LIMIT 10;


-- 8.Display the average order value for each customer.

SELECT
    o.customer_id,
    ROUND(AVG(op.payment_value), 2) AS average_order_value
FROM orders o
JOIN order_payments op
    ON o.order_id = op.order_id
GROUP BY o.customer_id
ORDER BY average_order_value DESC;


-- 9.Calculate the total freight cost collected by each seller.

SELECT 
    s.seller_id,
    s.seller_city,
    s.seller_state,
    ROUND(SUM(oi.freight_value), 2) AS total_freight_cost
FROM
    sellers s
        JOIN
    order_items oi ON s.seller_id = oi.seller_id
GROUP BY s.seller_id , s.seller_city , s.seller_state
ORDER BY total_freight_cost DESC;


-- 10.Find the top 5 product categories generating the highest revenue.

SELECT
    p.product_category_name,
    ROUND(SUM(oi.price), 2) AS total_revenue
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY p.product_category_name
ORDER BY total_revenue DESC
LIMIT 5;


-- 11.Display the average delivery time (in days) for each state.

SELECT
    c.customer_state,
    ROUND(
        AVG(DATEDIFF(o.order_delivered_customer_date,
                     o.order_purchase_timestamp)), 2
    ) AS avg_delivery_days
FROM orders o
JOIN customers c
    ON o.customer_id = c.customer_id
WHERE o.order_delivered_customer_date IS NOT NULL
GROUP BY c.customer_state
ORDER BY avg_delivery_days DESC;


-- 12.Find orders that were delivered later than the estimated delivery date.
SELECT
    order_id,
    customer_id,
    order_purchase_timestamp,
    order_estimated_delivery_date,
    order_delivered_customer_date,
    DATEDIFF(order_delivered_customer_date, order_estimated_delivery_date) AS delayed_days
FROM orders
WHERE order_delivered_customer_date > order_estimated_delivery_date
ORDER BY delayed_days DESC;


-- 13.Calculate monthly sales revenue.

SELECT
    YEAR(o.order_purchase_timestamp) AS order_year,
    MONTH(o.order_purchase_timestamp) AS order_month,
    ROUND(SUM(op.payment_value), 2) AS total_revenue
FROM orders o
JOIN order_payments op
    ON o.order_id = op.order_id
GROUP BY
    YEAR(o.order_purchase_timestamp),
    MONTH(o.order_purchase_timestamp)
ORDER BY
    order_year,
    order_month;


-- 14.Find Customers Who Spent More Than 5000

SELECT
    o.customer_id,
    ROUND(SUM(op.payment_value), 2) AS total_spent
FROM orders o
JOIN order_payments op
    ON o.order_id = op.order_id
GROUP BY o.customer_id
HAVING SUM(op.payment_value) > 5000
ORDER BY total_spent DESC;


-- 15.Rank Sellers Based on Total Revenue Using a Window Function

SELECT
    s.seller_id,
    s.seller_city,
    s.seller_state,
    ROUND(SUM(oi.price), 2) AS total_revenue,
    RANK() OVER (ORDER BY SUM(oi.price) DESC) AS seller_rank
FROM sellers s
JOIN order_items oi
    ON s.seller_id = oi.seller_id
GROUP BY
    s.seller_id,
    s.seller_city,
    s.seller_state
ORDER BY seller_rank;


-- 16.Calculate the percentage contribution of each payment type to total sales.

SELECT
    payment_type,
    ROUND(SUM(payment_value), 2) AS total_sales,
    ROUND(
        (SUM(payment_value) * 100.0) /
        (SELECT SUM(payment_value) FROM order_payments),
        2
    ) AS sales_percentage
FROM order_payments
GROUP BY payment_type
ORDER BY total_sales DESC;

-- 17. Create a sales dashboard report showing:
-- Total Customers
-- Total Orders
-- Total Revenue
-- Average Order Value
-- Total Sellers
-- Delivered Orders %
-- Cancelled Orders %
-- Top Product Category
-- Top Seller
-- Monthly Revenue Trend

SELECT
    (SELECT COUNT(*) FROM customers) AS total_customers,

    (SELECT COUNT(*) FROM orders) AS total_orders,

    (SELECT ROUND(SUM(payment_value),2)
     FROM order_payments) AS total_revenue,

    (SELECT ROUND(AVG(payment_value),2)
     FROM order_payments) AS average_order_value,

    (SELECT COUNT(*) FROM sellers) AS total_sellers,

    (SELECT COUNT(*)
     FROM products) AS total_products,

    (SELECT COUNT(*)
     FROM orders
     WHERE order_status = 'delivered') AS delivered_orders,

    (SELECT COUNT(*)
     FROM orders
     WHERE order_status = 'canceled') AS cancelled_orders,

    (SELECT ROUND(
        COUNT(*) * 100.0 /
        (SELECT COUNT(*) FROM orders),2)
     FROM orders
     WHERE order_status = 'delivered') AS delivered_percentage,

    (SELECT ROUND(
        COUNT(*) * 100.0 /
        (SELECT COUNT(*) FROM orders),2)
     FROM orders
     WHERE order_status = 'canceled') AS cancelled_percentage;